config/routes.rb
Rails.application.routes.draw do



  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do

    root 'static_pages#home_offline'
    
    get 'places/create'
    get 'places/index'
    get 'friends/index'
    get 'friends/destroy'
    get 'sessions/new'
    
    get 'terms' => 'static_pages#terms'
    get 'signup' => 'users#new'
    get 'objectives' => 'static_pages#objectives'
    
    get 'login' => 'static_pages#home_offline'
    post 'login' => 'sessions#create'
    
    delete 'logout' => 'sessions#destroy'
    get 'homepage' => 'static_pages#home_offline'
    get 'dashboard' => 'static_pages#dashboard'
    get 'settings' => 'static_pages#settings'
    get 'terms_of_use' => 'static_pages#terms_of_use'
    get 'contact_us' => 'static_pages#contact_us'
    get 'faq' => 'static_pages#faq'

    get 'safety' => 'static_pages#safety'
    get 'place/:place_id', :to => 'places#show'

    get 'unauthorized_access' => 'static_pages#home_offline'
    get 'not_found' => 'static_pages#home_offline'

    get 'react_test' => 'static_pages#react_test'

    get 'event_coorganizers' => 'data#event_coorganizers'

    # get 'photos' => 'photos#index'
    
    resources :users do
      resources :cover_pictures
      resources :friendships, only: [:index, :destroy]  
      resources :photos, only: [:index]    
      resources :pictures
      resources :profile_pictures
      resources :stories, only: [:index, :destroy]
      resources :replies
      resources :subscriptions
    end

    resources :notifications, only: [:index, :show, :create, :destroy]
    #updates all param
    resources :notifications do
        collection do
            put 'update_all'
            #put so is not caught in the controller correct_user method's logic
            put 'destroy_all'
        end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :password_updates, only: [:create]
    resources :email_updates, only: [:create]
    resources :places
    resources :friend_requests
    resources :travel_threads, except: [:edit, :update, :destroy] 
    resources :conversations
    resources :messages, only: [:create]
    resources :user_languages
    resources :user_places
    resources :suggestions
    resources :stories, only: [:new, :create, :edit, :update, :destroy]
    resources :invitations, only: [:create]
    resources :stories, only: [:new]
    resources :redirects, only: [:create, :show]
    resources :events, only: [:create, :new, :edit, :update, :index, :destroy, :show]
  end

  

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

	default_scope -> {order(updated_at: :desc)}

	has_many :user_conversations, inverse_of: :conversation
	has_many :users, through: :user_conversations
	has_many :messages, inverse_of: :conversation

	accepts_nested_attributes_for :user_conversations
	accepts_nested_attributes_for :messages

	before_validation :set_privacy, on: :create
	before_validation :set_nested_message_conversation

	#can message up to a maximum of 20 users
	validates :user_conversations, length: {minimum: 2, maximum: 21, message: :recipients}
	validates :messages, length: {is: 1}
	validates_inclusion_of :private, in: [true, false]
	
	validate :no_repeating_ids, on: :create
	validate :private_conversation_exists?, on: :create
	#must validate on creation so that it doesn't reach the DB

	before_create :set_user_conversations_read_status, on: :create

	def mark_conversation_as_read(user)
		@user_conversation = UserConversation.where(user_id: user.id, conversation_id: self.id).first
		@user_conversation.mark_as_read
	end


	#verifies if a private conversation exists
	def find_private_conversation
		if self.user_conversations.length == 2
			user1 = self.user_conversations.first.user
			user2 = self.user_conversations.last.user

			user_conversations = user1.user_conversations.includes(:user, :conversation)

			user_conversations.each do |user_conversation|
				users_ids = user_conversation.conversation.users.ids

				if (users_ids.sort == [user1.id, user2.id].sort) && (users_ids.length == 2)
					return user_conversation.conversation
				end
			end
			return nil
		end
	end

	def find_user_conversation(user)
		user_conversation = UserConversation.where(conversation_id: self.id, user: user.id).first
	end

	private

		def no_repeating_ids
			user_ids = Array.new
			self.user_conversations.each do |uc|
				user_ids.push(uc.user_id)
			end
			errors.add(:conversation, "cannot add repeated users") unless user_ids.length == user_ids.uniq.length
		end

		def private_conversation_exists?
			if self.find_private_conversation
				errors.add(:conversation, "cannot create a private conversation again")
			end
		end

		def set_privacy
			if self.user_conversations.length == 2
				self.private = true
			else
				self.private = false
			end
			#must return to otherwise it will return false
			#when the the number of ucs is less than 2 and 
			#will stop all the callbacks from running.
			#in other words it won't save
			return true
		end

		def set_nested_message_conversation
			self.messages.first.conversation = self
		end

		def set_user_conversations_read_status
			user_conversations = self.user_conversations
			#first user is the current_user

			user_conversations.each_with_index do |u_c, index|
				if index == 0
					u_c.read=(true)
				else
					u_c.read=(false)
				end
			end
		end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :logged_in_user, :completed_profile
	before_action :correct_user, only: [:show]

	def index
		@conversation = nil #to show conversation in case it exists
		@control_flag = "index_conversations"
		if messaging_other_user?
			@recipient = User.find_by_id(params[:message_to])
			if @recipient 
				if (conversation_id = conversation_exists?(current_user, @recipient))
					@conversation = Conversation.where(id: conversation_id).includes(:messages).first
					@messages = @conversation.messages
					@control_flag = "conversation_found"
				else
					@control_flag = "new_conversation"
				end
			else
				@control_flag = "invalid recipient"
				flash.now[:notice] = "User being messaged doesn't exist"
			end
		end
		@conversations = current_user.conversations.all.includes(:users, :user_conversations, :messages)
		@message = Message.new
		@new_conversation = Conversation.new
		@new_conversation_message = @new_conversation.messages.build

		if @control_flag == "new_conversation"
			#removes the user from the friends list if it exists so it's not added as a tag
			#and the autocomplete at the same time
			@recipients_list = build_recipients_list current_user.friends, @recipient
		else
			@recipients_list = current_user.friends
		end	
	end

	def create
		@conversation = Conversation.new(conversation_params)
		@existing_conversation = @conversation.find_private_conversation
		if @conversation.save || @existing_conversation
			@control_variable = "create_conversation"
			if @existing_conversation
				@message = @conversation.messages.first
				@conversation = @existing_conversation
				#must add message to the conversation
				@conversation.messages << @message
				@control_variable = "conversation_exists"
			end
			@messages = @conversation.messages.all.includes(:user)
			@message_count = 0
			@recipients_names = @conversation.users.pluck(:firstname)
			
			respond_to do |format|
				#redirected to this callback to prevent duplicate logic
				format.js {render 'conversations/show.js.erb'}
			end
		else
			pass_to_error_handler @conversation.errors
		end
	end

	def show
		@conversation = Conversation.find(params[:id])
		@conversation.mark_conversation_as_read(current_user)
		@messages = @conversation.messages.all.includes(:user)
		@firstnames = @conversation.users.pluck(:firstname)
		#so the current_user.firstname doesn't show on the recipients list
		@recipients_names = ( (name_formatter @firstnames) - [current_user.firstname])
		@control_variable = "show_conversation"
		respond_to do |format|
			format.js {render 'conversations/show.js.erb'}
		end
	end

	private 
		def conversation_params
			params.require(:conversation).permit(messages_attributes:[:content, :user_id], 
				user_conversations_attributes:[:user_id])
		end

		def messaging_other_user?
			return (current_user.id != params[:message_to] && !params[:message_to].nil?)
		end

		def completed_profile
			profile_complete = current_user.profile_complete?
			if !profile_complete
				flash[:notice] =  t('alerts.notice.conversation.complete_profile')
				redirect_to current_user
			end
		end

end

app/helpers/conversations_helper.rb
module ConversationsHelper

	def conversation_exists?(user1, user2)
		user_conversations = user1.user_conversations.includes(:user, :conversation)

		user_conversations.each do |user_conversation|
			users_ids = user_conversation.conversation.users.ids

			if (users_ids.sort == [user1.id, user2.id].sort) && (users_ids.length == 2)
				return user_conversation.conversation.id
			end
		end

		return false
	end

	def find_thumbnail_users(messages)
		users_ids = Conversation.find(messages.first.conversation.id).users.ids
		users_ids = users_ids - [current_user.id] #removes current user_id
		users = User.where(id: users_ids)
		return users
	end

	#excludes current user
	def participants_names(users)
		firstnames = users.pluck(:firstname)
		return firstnames.join(", ")
	end

	def build_recipients_data(users)
		recipients = []
		users.each do |user|
			recipient = {}
			recipient[:fullname] = user.fullname
			recipient[:id] = user.id
			recipients << recipient
		end
		return recipients.to_json
	end

	#function used to remove columns from query, i.e. tokens
	#patch solution due to 
	#select syntax not working for activeRecord
	def filter_user_data_as_json(users, params=[])
		filtered_users = []
		if params.length == 0
			users.each do |u|
				filtered_user = {}
				filtered_user[:fullname] = u.fullname
				filtered_user[:id] = u.id
				filtered_users << filtered_user
			end
		end
		return filtered_users.to_json
	end

	def unread_messages?(messages, unread_messages)
		if unread_messages.length > 0
			messages_ids = messages.ids
			unread_messages.each do |unread_message|
				if messages_ids.include? unread_message.message_id
					return true
				end
			end
		end
		return false
	end

	#removes recipient in case it exists
	def build_recipients_list (friends, recipient)
		if friends.include? recipient
			filtered = friends.each.reject { |friend| friend.id == recipient.id }
			return filtered
		end
		return friends
	end
end

app/views/conversations/_conversation.html.haml
- messages = conversation.messages

- users = find_thumbnail_users (messages)
- user = users.first
- user_conversation = conversation.find_user_conversation current_user

- classes = 'conversation-thumbnail '

- if user_conversation.unread?
	- classes << 'unread'

= link_to conversation_path(id: conversation.id), method: :get, remote: true, conversation_id: conversation.id, class: classes do
	.last-date= time_ago_in_words(conversation.messages.last.created_at)
	.user-pic
		= show_profile_illustration user, user.current_profile_picture, ["profile-image-conversation"], true
	.user-text
		.fullname= participants_names(users)
		.last-message= conversation.messages.last.content

app/views/conversations/_form.html.haml
- sending = t('general.sending')

-if hidden == true
	-style = "display: none"
-else
	-style = "display: block"
= form_for (@new_conversation), html: {style: style}, remote: true do |f|
	= f.fields_for :messages do |message|
		= message.text_area :content, placeholder: t('general.enter_message')
		= message.hidden_field :user_id, value: current_user.id
	= f.hidden_field 'user_conversations_attributes][0][user_id]', value: current_user.id
	#recipients-list
		- if recipient
			= f.hidden_field 'user_conversations_attributes][1][user_id]', value: recipient.id
	/ populated with JavaScript
	.actions
		= f.submit t('general.send_message'), class: 'send-message-button', data: {disable_with: sending}

app/views/conversations/failed_create.js.erb
Tabilocal.notificationHandler.create("Could not create conversation", "error");

app/views/conversations/index.html.haml
-if @control_flag == "conversation_found"
  - header_name = @recipient.fullname
  - style = "display: none"
-else
  - header_name = t(".new_message")
  - style = "display: block"


.conversation-selector.col-4.col-sm-12.col-xs-12
  .search-input
    .search-box
      %input{placeholder: t('general.search'), type: 'text', id: 'filter-conversations'}
    .search-button
      %i.fa.fa-search
  .conversations
    - if @conversations.count > 0
      = render @conversations
    - else
      = render partial: "shared/alert_message", locals: {class_name: "notice", message: t("alerts.notice.conversation.empty"), fixed: false, static: true}

.conversation-log.col-8.col-sm-12.col-xs-12
  .conversation-header
    .header-name= header_name
    .new-conversation-button= t(".new_conversation")
    .recipients-list{style: style}
      .to Para:
      .nametags-wrapper
        - if @control_flag == "new_conversation"
          .nametag
            %span{class: 'fullname', id: "#{@recipient.id}"}= @recipient.fullname
            %span.close-button
              %i.fa.fa-times
        .autocomplete#inbox-autocomplete
          %input{placeholder: t('.enter_name'), type: 'text', class: 'name-input atc', id: 'recipients-input'}
        
  .messages.grid-container
    -if @conversation 
      = render @conversation.messages

  - if @control_flag == "conversation_found"
    = render partial: 'messages/form', locals: {conversation_id: @conversation.id, hidden: false}
    = render partial: 'conversations/form', locals: {hidden: true, recipient: nil}
  - if @control_flag == "index_conversations" || @control_flag == "invalid recipient"
    = render partial: 'messages/form', locals: {conversation_id: nil, hidden: true}
    = render partial: 'conversations/form', locals: {hidden: false, recipient: nil}
  - if @control_flag == "new_conversation" 
    = render partial: "messages/form", locals: {conversation_id: nil, hidden: true}
    = render partial: 'conversations/form', locals: {hidden: false, recipient: @recipient}

- recipients_data = filter_user_data_as_json @recipients_list
.recipients-json{:data => "#{recipients_data}"}

app/views/conversations/new.html.haml
= render 'shared/conversation_form'

app/views/conversations/show.html.haml
%ul#messages-list
	- @messages.each do |message|
		%li= message.user.fullname + " said: " + message.content

= form_for(@message, remote: true) do |f|
	= render 'shared/error_messages', object: f.object
	= f.hidden_field :conversation_id, value: @conversation.id
	= f.text_area :content
	= f.submit "Send message", class: 'btn'

app/views/conversations/show.js.erb
conversationHtml = "<%= escape_javascript (render @conversation) %>";
conversationId = parseInt("<%= escape_javascript (@conversation.id.to_s )%>");

Tabilocal.messages.enableForm();
Tabilocal.messages.setLog("<%= escape_javascript ( render @messages ) %>");
Tabilocal.messages.setConversationId(conversationId);
Tabilocal.inbox.recipients.set(JSON.parse("<%= escape_javascript(@recipients_names.to_json.html_safe) %>"));
Tabilocal.inbox.recipients.hideSendHeader();

<% if @control_variable == 'create_conversation' %>
	Tabilocal.inbox.conversations.insertNew(conversationHtml);
<% else %>
//One conversation is read
	Tabilocal.messages.updateUnreadCount(1);
<% end %>

<% if @control_variable == 'conversation_exists' %>
	// Tabilocal.notificationHandler.create("The conversation with this user already exists", "notice");
	// notice is commented out as it's obvious the conversation exists
<% end %>

Tabilocal.inbox.conversations.markAsSelected(conversationId);

conversationHtml = null;
conversationId = null;