config/routes.rb
Rails.application.routes.draw do



  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do

    root 'static_pages#home_offline'
    
    get 'places/create'
    get 'places/index'
    get 'friends/index'
    get 'friends/destroy'
    get 'sessions/new'
    
    get 'terms' => 'static_pages#terms'
    get 'signup' => 'users#new'
    get 'objectives' => 'static_pages#objectives'
    
    get 'login' => 'static_pages#home_offline'
    post 'login' => 'sessions#create'
    
    delete 'logout' => 'sessions#destroy'
    get 'homepage' => 'static_pages#home_offline'
    get 'dashboard' => 'static_pages#dashboard'
    get 'settings' => 'static_pages#settings'
    get 'terms_of_use' => 'static_pages#terms_of_use'
    get 'contact_us' => 'static_pages#contact_us'
    get 'faq' => 'static_pages#faq'

    get 'safety' => 'static_pages#safety'
    get 'place/:place_id', :to => 'places#show'

    get 'unauthorized_access' => 'static_pages#home_offline'
    get 'not_found' => 'static_pages#home_offline'

    get 'react_test' => 'static_pages#react_test'

    get 'event_coorganizers' => 'data#event_coorganizers'

    # get 'photos' => 'photos#index'
    
    resources :users do
      resources :cover_pictures
      resources :friendships, only: [:index, :destroy]  
      resources :photos, only: [:index]    
      resources :pictures
      resources :profile_pictures
      resources :stories, only: [:index, :destroy]
      resources :replies
      resources :subscriptions
    end

    resources :notifications, only: [:index, :show, :create, :destroy]
    #updates all param
    resources :notifications do
        collection do
            put 'update_all'
            #put so is not caught in the controller correct_user method's logic
            put 'destroy_all'
        end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :password_updates, only: [:create]
    resources :email_updates, only: [:create]
    resources :places
    resources :friend_requests
    resources :travel_threads, except: [:edit, :update, :destroy] 
    resources :conversations
    resources :messages, only: [:create]
    resources :user_languages
    resources :user_places
    resources :suggestions
    resources :stories, only: [:new, :create, :edit, :update, :destroy]
    resources :invitations, only: [:create]
    resources :stories, only: [:new]
    resources :redirects, only: [:create, :show]
    resources :events, only: [:create, :new, :edit, :update, :index, :destroy, :show]
  end

  

end

app/models/notification.rb
class Notification < ActiveRecord::Base

	# default_scope { includes(:notificationable) }

	default_scope -> {order(created_at: :desc)}
	

	after_initialize :set_unread_status

	validate :check_unread_status, on: :create

	belongs_to :notificationable, polymorphic: true
	belongs_to :user

	VALID_TYPE_REGEX = /\A(Reply|Friendship|Story)\z/

	validates :notificationable_type, format: {with: VALID_TYPE_REGEX}
	validates :notificationable_id, presence: true
	validates :user_id, presence: true

	def mark_as_read
		self.update(read: true)		
	end

	private 
		def check_unread_status
			errors.add(:notification, "status cannot be unread upon creation") unless self.read == false
		end

		def set_unread_status
			if self.new_record?
				self.read = false
			end
		end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :logged_in_user 
  before_action :correct_user, only: [:show, :destroy]

  STORY = "Story"
  FRIENDSHIP = "Friendship"
  REPLY = "Reply"
  
  def show
    @notification = Notification.find_by_id(params[:id])
    if @notification
      @notification.mark_as_read

    	notification_type = case @notification.notificationable_type

    		when STORY then 
          redirect_to user_stories_path(user_id: current_user.id)
    		when FRIENDSHIP then 
          @friendship = @notification.notificationable
          redirect_to user_path(id: @friendship.friend.id)
    		when REPLY then 
          @reply = @notification.notificationable
          @travel_thread = @reply.replyable
          redirect_to travel_thread_path(id: @travel_thread.id, anchor: (generate_anchor @reply))
    	end
    else
    	flash[:notice] = t('alerts.notice.notification.does_not_exist')
    	redirect_to current_user
    end
  end

  def index
    @notifications = current_user.notifications
    render :index
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification_id = @notification.id
    if @notification.destroy
      render 'notifications/destroy.js.erb'
    else
      pass_to_error_handler @notification.errors
    end
  end

  def update_all
    @notifications = current_user.notifications
    @notifications.update_all(read: true)
    render 'notifications/mark_all_as_read.js'
  end

  def destroy_all
    @notifications = current_user.notifications
    @notifications.destroy_all
    render 'notifications/remove_all.js'
  end
  

end

app/helpers/notifications_helper.rb
module NotificationsHelper

	#This method contains logic at the view level
	def show_delete_button?(notification)
		if controller.controller_name == "notifications" &&
			controller.action_name == "index" &&
			notification.user_id == current_user.id
			return true
		else
			return false
		end
	end
end

app/views/notifications/_notification.html.haml
-if notification.notificationable_type == "Story"
	-user = notification.notificationable.user
	-description = t('notifications.description.wrote_story')
	-username = user.fullname
-if notification.notificationable_type == "Reply"
	-user = notification.notificationable.user
	-description = t('notifications.description.responded_thread')
	-username = user.fullname
-if notification.notificationable_type == "Friendship"
	-user = notification.notificationable.friend
	-description = t('notifications.description.accepted_request')
	-username = user.fullname

- read_class = notification.read ? "read" : "unread"
%li{class: read_class + " notification notification-#{notification.id}"}
	= link_to notification_path(notification), class: "link" do
		.profile-image-wrapper.col-4
			= show_profile_illustration user, user.current_profile_picture, ["profile-image-notification"], true
		.notification-wrapper.col-8
			.username= username
			.notification= description

		-if show_button == true && current_user.id == notification.user_id
			= button_to notification_path(id: notification.id), method: :delete,  remote: true, class: 'remove-button' do        
				%i.fa.fa-times
		.published-date= time_ago_in_words (notification.created_at)

	-#button only show at the index level - not at the partial level
	-# the last condition may not be needed as index controller only returs
	-# the notifications that belong to current_user

app/views/notifications/destroy.js.erb
Tabilocal.notifications.remove("<%= j @notification.id.to_s %>");

app/views/notifications/index.html.haml
.notifications-container
	%h4.header= t('.header')

	.dropdown-trigger
		%i.fa.fa-caret-down
	.buttons-container
		= button_to t('notifications.mark_all_as_read'), update_all_notifications_path, method: :put, remote: true, class: 'mark-read-button'
		= button_to t('general.delete_all'), destroy_all_notifications_path, class: 'remove-all-button', method: :put, remote: true

	%ul.notifications-index
		= render partial: 'notifications/notification', collection: @notifications, locals: {show_button: true}

		.no-notifications-notice
			= render partial: 'shared/alert_message', locals: {message: "No tienes notificaciones", class_name: "notice", fixed: false, static: true}