config/routes.rb
Rails.application.routes.draw do



  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do

    root 'static_pages#home_offline'
    
    get 'places/create'
    get 'places/index'
    get 'friends/index'
    get 'friends/destroy'
    get 'sessions/new'
    
    get 'terms' => 'static_pages#terms'
    get 'signup' => 'users#new'
    get 'objectives' => 'static_pages#objectives'
    
    get 'login' => 'static_pages#home_offline'
    post 'login' => 'sessions#create'
    
    delete 'logout' => 'sessions#destroy'
    get 'homepage' => 'static_pages#home_offline'
    get 'dashboard' => 'static_pages#dashboard'
    get 'settings' => 'static_pages#settings'
    get 'terms_of_use' => 'static_pages#terms_of_use'
    get 'contact_us' => 'static_pages#contact_us'
    get 'faq' => 'static_pages#faq'

    get 'safety' => 'static_pages#safety'
    get 'place/:place_id', :to => 'places#show'

    get 'unauthorized_access' => 'static_pages#home_offline'
    get 'not_found' => 'static_pages#home_offline'

    get 'react_test' => 'static_pages#react_test'

    get 'event_coorganizers' => 'data#event_coorganizers'

    # get 'photos' => 'photos#index'
    
    resources :users do
      resources :cover_pictures
      resources :friendships, only: [:index, :destroy]  
      resources :photos, only: [:index]    
      resources :pictures
      resources :profile_pictures
      resources :stories, only: [:index, :destroy]
      resources :replies
      resources :subscriptions
    end

    resources :notifications, only: [:index, :show, :create, :destroy]
    #updates all param
    resources :notifications do
        collection do
            put 'update_all'
            #put so is not caught in the controller correct_user method's logic
            put 'destroy_all'
        end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :password_updates, only: [:create]
    resources :email_updates, only: [:create]
    resources :places
    resources :friend_requests
    resources :travel_threads, except: [:edit, :update, :destroy] 
    resources :conversations
    resources :messages, only: [:create]
    resources :user_languages
    resources :user_places
    resources :suggestions
    resources :stories, only: [:new, :create, :edit, :update, :destroy]
    resources :invitations, only: [:create]
    resources :stories, only: [:new]
    resources :redirects, only: [:create, :show]
    resources :events, only: [:create, :new, :edit, :update, :index, :destroy, :show]
  end

  

end

app/models/travel_thread.rb
class TravelThread < ActiveRecord::Base

	after_initialize :set_replies_to_zero, on: :create

	belongs_to :user
	belongs_to :language
	belongs_to :place

	has_many :replies, as: :replyable
	has_many :taggings, as: :taggable
	has_many :tags, through: :taggings
	has_many :subscriptions, as: :subscriptionable

	accepts_nested_attributes_for :replies
	accepts_nested_attributes_for :taggings
	accepts_nested_attributes_for :subscriptions
	
	validates :title, presence: {message: :presence}, length: {minimum: 6, message: :length} 
	validates :user_id, presence: true
	validates :language_id, presence: true
	validates :place_id, presence: {message: :blank}

	validates :replies, presence: true, length: {is: 1}, on: :create
	validates :taggings, presence: {message: :blank}, length: {minimum: 1, maximum: 3, message: :maximum}, on: :create
	
    validate :correct_user_language, on: :create
    validate :match_reply_user, on: :create
    validate :match_subscription_user, on: :create

    after_create :update_place_count
  
	def user_language_exists?(user_id, language_id)
		ul = UserLanguage.where(user_id: user_id, language_id: language_id)
		return (ul.length == 1)
	end

	private

		def correct_user_language
			errors.add(:travel_thread, "must choose correct language") unless user_language_exists?(self.user_id, self.language_id) 
		end

		def match_reply_user
			if self.replies.length > 0
				errors.add(:travel_thread, "travel thread's and reply's ids must match") unless self.user_id == self.replies.first.user_id
			end
		end

		def match_subscription_user
			if self.subscriptions.length > 0
				errors.add(:travel_thread, "travel thread's and subscription's ids must match") unless self.user_id == self.subscriptions.first.user_id
			end
		end

		def set_replies_to_zero
			if self.new_record?
				self.replies_count = 0
			end
		end

		def update_place_count
			place = Place.find(self.place_id)
			count = place.threads
			place.update_column(:threads, (count + 1))
		end
end

app/controllers/travel_threads_controller.rb
class TravelThreadsController < ApplicationController

	before_action :logged_in_user
	before_action :verify_language_count
	before_action :current_languages, only: [:index, :show]
	before_action :verify_correct_language, only: [:show]

	JSON_INCLUDE_PARAMS = [:place, :language, :tags, :user]
	#MUST MATCH VALUE ON DASHBOARD CONTROLLER
	THREADS_PER_PAGE = 10
	#TravelThread.includes(:tags).where(:tags => {id: [1,2,3]}).all

	def index
		@tags = Tag.all
		respond_to do |format|
			format.json do
				 #add fltering for languages
				 #where places.country "Japan"
				 @travel_threads = TravelThread.all.includes(:place, :language, :tags).where("languages.id" => @current_languages.ids)
				 render json: @travel_threads.as_json(:include=>JSON_INCLUDE_PARAMS), status: 200
			end
			format.html do
				@filter = params[:sort]
				case @filter
				when "unanswered"
					@travel_threads = TravelThread.all.includes(:place, :language, :tags, :user) #no replies is one reply (opening post)
								.where("languages.id" => @current_languages.ids, "replies_count" => 1)
								.paginate(page: params[:page], per_page: THREADS_PER_PAGE)
				when "most_popular"
					@travel_threads = TravelThread.all.includes(:place, :language, :tags, :user)
								.where("languages.id" => @current_languages.ids)
								.paginate(page: params[:page], per_page: THREADS_PER_PAGE).order(replies_count: :desc)
				else
					@travel_threads = TravelThread.all.includes(:place, :language, :tags, :user)
								.where("languages.id" => @current_languages.ids)
								.paginate(page: params[:page], per_page: THREADS_PER_PAGE).order(updated_at: :desc)
				end

				render @travel_threads
									
		 	 	# if @travel_threads.length == 0
		 	 	# 	render @travel_threads, status: 304
		 	 	# else
		 	 	# 	render @travel_threads, status: 200
		 	 	# end
			end
		end
	end

	def show
		# so the partial comes out right
		@replies = @thread.replies
		@reply = Reply.new
		@existing_subscription = current_user.subscriptions.find_by(
			subscriptionable_type: @thread.class.name,
			subscriptionable_id: @thread.id)
		@new_subscription = current_user.subscriptions.build
	end

	def new
		@travel_thread = current_user.travel_threads.build
		@reply = @travel_thread.replies.build
		@subscription = @travel_thread.subscriptions.build
		@my_languages = current_languages
		@tags = Tag.where(category: "T")
	end

	def create
		@travel_thread = current_user.travel_threads.build(travel_thread_params)
		if @travel_thread.save	
			flash[:success] = t('alerts.success.thread.created')
			render js: "window.location='#{travel_thread_path(@travel_thread)}'"
		else
			@errors = @travel_thread.errors
			render 'layouts/errorHandler.js.erb'
		end
	end

	# def query
	# 	if params[:query] == 'true'
	# 	query_params = build_query_params(params)
    #  	@travel_threads = TravelThread.all.includes(:place, :language, :tags).where(query_params)
	# end

	private

		def travel_thread_params
			params.require(:travel_thread).permit(:title, :user_id, :language_id, :place_id, 
				replies_attributes: [:content, :user_id, :first], taggings_attributes: [:tag_id], 
				subscriptions_attributes: [:user_id])
		end

		def verify_correct_language
			@thread = TravelThread.find(params[:id])
			if !(@current_languages.ids.include? @thread.language.id)
				flash[:notice] = "You must speak the language of the thread you're trying to see" 
				redirect_to current_user
			end
		end

end

app/views/travel_threads/_guidelines.html.haml
.row
  .col-6.col-sm-12.col-xs-12
    %h5= t('.caution_header')
    .caution
      %i.fa.fa-exclamation-triangle
      %p
        %span= t('.caution_one_i')
        =link_to (t('.link_to_terms')), terms_of_use_path, target: '_blank'
        %span= t('.caution_one_ii')
    .caution
      %i.fa.fa-exclamation-triangle
      %p
        %span= t('.caution_two_i')
        =link_to (t('.link_to_contact_caution_two')), contact_us_path, target: '_blank'
        %span= t('.caution_two_ii')
    .caution
      %i.fa.fa-exclamation-triangle
      %p
        %span= t('.caution_three_i')
        =link_to (t('.link_to_contact_caution_three')), contact_us_path, target: '_blank'
        %span= t('.caution_three_ii')
        =link_to (t('.link_to_faq')), faq_path, target: '_blank'
        %span= t('.caution_three_iii')
  .col-6.col-sm-12.col-xs-12
    %h5= t('.tips_header')
    .tip
      %i.fa.fa-check
      %p= t('.tip_one')
    .tip
      %i.fa.fa-check
      %p= t('.tip_two')

app/views/travel_threads/_travel_thread.html.haml
- filtering_data = build_filtering_object(travel_thread)

.thread{"thread-data": "#{filtering_data}"}
	.posted-date
		= time_ago_in_words (travel_thread.updated_at)

	.author-thumbnail.hyperlink
		= link_to travel_thread.user do
			= show_profile_illustration travel_thread.user, travel_thread.user.current_profile_picture, ["profile-image-forum"], true
			= travel_thread.user.firstname
		
	.number-of-replies
		.number
			= travel_thread.replies_count - 1
		%span.replies
			= Reply.model_name.human(count: (travel_thread.replies_count - 1))
		
	.tags-container
		= render partial: 'tags/tag', collection: travel_thread.tags

	.thread-summary
		=link_to(travel_thread, class: 'thread-title hyperlink') do
			= travel_thread.title
		%span.location
			%span=t('general.thread_location')
			= link_to (place_formatter travel_thread.place, "with_country"), place_path(travel_thread.place), class: 'city-state hyperlink'

app/views/travel_threads/index.html.haml
.forum-container
	= link_to new_travel_thread_path, class: 'ask-question-button' do
		= t('.ask_question_button')

	.forum-header
		%p= t('.forum_header_one')
		%p= t('.forum_header_two')

	%ul.filtering-box
		- if !Rails.env.production?
			%li{class: 'filtering-tab', 'data-attr' => 'tags'}= t('.filtering_option_tag')
			%li{class: 'filtering-tab', 'data-attr' => 'languages'}= t('.filtering_option_language')
			%li{class: 'filtering-tab', 'data-attr' => 'countries'}= t('.filtering_option_location')
		-else
			%li{class: 'filtering-tab full-width', 'data-attr' => 'tags'}= t('.filtering_option_tag')

		%div{class: 'filtering-options tags-container', 'data-attr' => 'tags'}
			= render partial: 'tags/tag', collection: @tags, locals: {selectable: true, queryable: true}
		%div{class: 'filtering-options tags-container', 'data-attr' => 'languages'}
			=@current_languages.each do |language|
				%span{class: 'tag selectable', :queryable => 'true', 'queryable-category' => 'languages', "queryable-keyword" => "#{language.name}"}= language.name 
		%div{class: 'filtering-options tags-container', 'data-attr' => 'countries'}
			=@countries.each do |country|
				%span{class: 'tag selectable', :queryable => 'true', 'queryable-category' => 'places', 'queryable-keyword' => "#{country.name}"}= country.name  

		.reset-filter-button
			%i.fa.fa-trash
			= t('.reset_filter_button')

	%ul.tabs.thread-groups
		- case @filter
		- when "unanswered"
			%li.tab-link
				= link_to t('.latest_threads'), travel_threads_path
			%li.tab-link
				= link_to t('.popular_threads'), travel_threads_path(sort: :most_popular)
			%li.tab-link.current
				= link_to t('.unanswered_threads'), travel_threads_path(sort: :unanswered)
		- when "most_popular"
			%li.tab-link
				= link_to t('.latest_threads'), travel_threads_path
			%li.tab-link.current
				= link_to t('.popular_threads'), travel_threads_path(sort: :most_popular)
			%li.tab-link
				= link_to t('.unanswered_threads'), travel_threads_path(sort: :unanswered)
		- else
			%li.tab-link.current
				= link_to t('.latest_threads'), travel_threads_path
			%li.tab-link
				= link_to t('.popular_threads'), travel_threads_path(sort: :most_popular)
			%li.tab-link
				= link_to t('.unanswered_threads'), travel_threads_path(sort: :unanswered)

	#tab-1.tab-content.current.threads-container
		= render @travel_threads
		
	%button.load-more-button
		= t('general.load_more')

app/views/travel_threads/new.html.haml
- creating_thread = t(".posting_thread")
- set_language_id = 2

.guidelines-container.grid-container
	= render 'guidelines'

.new-thread-content
	%p= t('.pick_location')

	#travel-thread-autocomplete  
		%input{type: 'text', id: 'pac-threads', class: 'pac-input atc'}
	
	= form_for @travel_thread, remote: true do |f|
	
		= f.hidden_field :place_id, class: "form-place-id"
		= f.hidden_field :user_id, value: current_user.id
	
		-if !Rails.env.production?
			%p= t('.pick_language')
			= f.collection_select(:language_id, @my_languages, :id, :name)
		-else
			-#spanish is hardcoded in production
			= f.hidden_field :language_id, value: set_language_id
		
		%p= t('.pick_tags')
		.tags-container
			= render partial: 'tags/tag', collection: @tags, locals: {selectable: true}

		%p= t('.make_title')
		= f.text_field :title

		%p= t('.write_question')

		= render partial: 'layouts/editor_toolbar'

		= f.fields_for :replies do |replies|
			= replies.text_area :content, rows: 7
			= replies.hidden_field :user_id, value: current_user.id
			= replies.hidden_field :first, value: true

		.preview-container

		= f.fields_for :subscriptions do |subscriptions|
			= subscriptions.hidden_field :user_id, value: current_user.id

		#tags-container
		
		= f.submit t('.post_thread'), class: 'post-thread-button', data: {disable_with: creating_thread}

app/views/travel_threads/show.html.haml
- user = @thread.user

.thread-container
  #subscription-status
    - if @existing_subscription.nil?
      = render 'subscriptions/subscribe'
    -else
      = render 'subscriptions/unsubscribe'
      
  .thread-header
    .posted-date= time_ago_in_words @thread.created_at
    .tags-container
      = render partial: 'tags/tag', collection: @thread.tags
    .thread-title
      = @thread.title
    .location
      %span=t('general.thread_location')
      %a.city-state.hyperlink= @thread.place.name + ", " + @thread.place.country_assoc.name 
    .author
      %span=t('general.thread_author')
      = link_to user_path(id: user.id), class: 'hyperlink' do
        = show_profile_illustration user, user.current_profile_picture, ["profile-image-thread"], true
        .username= user.fullname
        
  #replies-list
    = render @replies 
  .text-input
    =render partial: 'replies/form'

app/views/travel_threads/travel_threads.js.erb
Tabilocal.threads.index.paginator.appendData("<%= escape_javascript( render @travel_threads) %>");