config/routes.rb
Rails.application.routes.draw do



  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do

    root 'static_pages#home_offline'
    
    get 'places/create'
    get 'places/index'
    get 'friends/index'
    get 'friends/destroy'
    get 'sessions/new'
    
    get 'terms' => 'static_pages#terms'
    get 'signup' => 'users#new'
    get 'objectives' => 'static_pages#objectives'
    
    get 'login' => 'static_pages#home_offline'
    post 'login' => 'sessions#create'
    
    delete 'logout' => 'sessions#destroy'
    get 'homepage' => 'static_pages#home_offline'
    get 'dashboard' => 'static_pages#dashboard'
    get 'settings' => 'static_pages#settings'
    get 'terms_of_use' => 'static_pages#terms_of_use'
    get 'contact_us' => 'static_pages#contact_us'
    get 'faq' => 'static_pages#faq'

    get 'safety' => 'static_pages#safety'
    get 'place/:place_id', :to => 'places#show'

    get 'unauthorized_access' => 'static_pages#home_offline'
    get 'not_found' => 'static_pages#home_offline'

    get 'react_test' => 'static_pages#react_test'

    get 'event_coorganizers' => 'data#event_coorganizers'

    # get 'photos' => 'photos#index'
    
    resources :users do
      resources :cover_pictures
      resources :friendships, only: [:index, :destroy]  
      resources :photos, only: [:index]    
      resources :pictures
      resources :profile_pictures
      resources :stories, only: [:index, :destroy]
      resources :replies
      resources :subscriptions
    end

    resources :notifications, only: [:index, :show, :create, :destroy]
    #updates all param
    resources :notifications do
        collection do
            put 'update_all'
            #put so is not caught in the controller correct_user method's logic
            put 'destroy_all'
        end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :password_updates, only: [:create]
    resources :email_updates, only: [:create]
    resources :places
    resources :friend_requests
    resources :travel_threads, except: [:edit, :update, :destroy] 
    resources :conversations
    resources :messages, only: [:create]
    resources :user_languages
    resources :user_places
    resources :suggestions
    resources :stories, only: [:new, :create, :edit, :update, :destroy]
    resources :invitations, only: [:create]
    resources :stories, only: [:new]
    resources :redirects, only: [:create, :show]
    resources :events, only: [:create, :new, :edit, :update, :index, :destroy, :show]
  end

  

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :subscriptionable, polymorphic: true
	belongs_to :user
	
	validates :user_id, presence: true

	VALID_TYPE_REGEX = /\A(TravelThread|LanguageThread)\z/
	validates :subscriptionable_type, format: {with: VALID_TYPE_REGEX}, allow_nil: true

	validates_uniqueness_of :user_id, scope: [:subscriptionable_type, :subscriptionable_id]

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

	before_action :logged_in_user
	before_action :correct_user, only: [:destroy]
	before_action :user_speaks_thread_language?, only: [:create]	


	def create
		@subscription = current_user.subscriptions.build(subscription_params)
		if @subscription.save
			@existing_subscription = @subscription
			respond_to do |format|
				format.js {render 'subscriptions/create_success.js.erb'}
			end
		else
			respond_to do |format|
				format.js {render 'subscriptions/create_error.js.erb'}
			end
		end
	end

	def destroy
		@subscription = Subscription.find_by(id: params[:id])
		if @subscription
			@thread = @subscription.subscriptionable #passes thread
			@subscription.destroy
			@new_subscription = current_user.subscriptions.build
			respond_to do |format|
				format.js {render 'subscriptions/destroy_success.js.erb'}
			end
		else 
			respond_to do |format|
				format.js {render 'subscriptions/destroy_error.js.erb'}
			end
		end

	end

	private

		def subscription_params
			params.require(:subscription).permit(:subscriptionable_type,
				:subscriptionable_id)
		end

end

app/views/subscriptions/_subscribe.html.haml
= form_for [current_user, @new_subscription], remote: true do |f|
  = f.hidden_field :subscriptionable_id, value: @thread.id
  = f.hidden_field :subscriptionable_type, value: @thread.class.name
  = f.submit t('general.subscribe_button'), class: 'subscribe-button'

app/views/subscriptions/_unsubscribe.html.haml
= link_to t('general.unsubscribe_button'), user_subscription_path(id: @existing_subscription.id, user_id: current_user.id), method: :delete, remote: true, class: 'subscribe-button'

app/views/subscriptions/create_error.js.erb
Tabilocal.notificationHandler.create("Could not subscribe	", "error");

app/views/subscriptions/create_success.js.erb
Tabilocal.notificationHandler.create("<%= I18n.t('alerts.success.subscription.added') %>", "success");
Tabilocal.subscriptions.renderSubscriptionBtn("<%= escape_javascript(render 'unsubscribe')%>");

app/views/subscriptions/destroy_error.js.erb
Tabilocal.notificationHandler.create("Could not unsubscribe", "error");

app/views/subscriptions/destroy_success.js.erb
Tabilocal.notificationHandler.create("<%= I18n.t('alerts.success.subscription.removed') %>", "success");
Tabilocal.subscriptions.renderSubscriptionBtn("<%= escape_javascript(render 'subscribe')%>");